### ISSUE TITLE
Can we get code for the IMD cloud node-RED flows too?

### ISSUE THREAD

**Issue by jsolderitsch** [johnwalicki/Node-RED-Onion-Omega2-Examples#1]
I am able to get some of these examples running on the new Omega Pro.

Some of them connect to node-RED logic running on the IBM cloud.

For example, Receive Weather Report from Watson IoT.

Are these available on GIthub or elsewhere?

**Comment by johnwalicki** [comment]
I pushed an example Node-RED IBM Cloud flow that uses Weather Underground to send the weather to the Onion.
flows/IBM-Cloud-NodeRED-Weather-WU.json

**Comment by jsolderitsch** [comment]
Thanks for the attention to this issue.

As I understand it, Weather Underground is no longer providing free API keys.

What advice would you give to get around this issue?

Jim

On Mar 5, 2019, at 12:03 AM, John Walicki <notifications@github.com<mailto:notifications@github.com>> wrote:


I pushed an example Node-RED IBM Cloud flow that uses Weather Underground to send the weather to the Onion.
flows/IBM-Cloud-NodeRED-Weather-WU.json

**Comment by johnwalicki** [comment]
Yep - I posted the IBM Cloud Node-RED flow that I wrote a few months ago. It uses the Weather Underground node.  The WU team has announced that their API is depreciated and will eventually be shut down.  The API still works - as of today - if you have an existing API key.  

A rewrite using the IBM Cloud Weather Insights service would not be difficult but I have no current plans for that.

**Comment by jsolderitsch** [comment]
Actually I made something work using Weather Insights. You can't use a Lite plan on IBM cloud though with that. It has to be at least a Pay-as-you-Go account. I was not a legacy member of the Weather Underground site so could not get a key.
