### ISSUE TITLE
Memory failure with Omega2+

### ISSUE THREAD

**Issue by jsolderitsch** [johnwalicki/Node-RED-Onion-Omega2-Examples#2]
Here is what I see:
``
root@Omega-FDDF:~# node --max_old_space_size=1024 $(which npm) -g install node-red-contrib-ibm-watson-iot
[            ......] | extract:bluebird: sill pacote bluebird@https://registry.npmjs.org/bluebird/-/bluebird-2.11.0.tgz extracted to /usr/lib/node_mod
<--- Last few GCs --->

[2133:0x127c000]   488277 ms: Scavenge 20.1 (23.2) -> 19.2 (23.2) MB, 1840.0 / 1279.1 ms  allocation failure 
[2133:0x127c000]   504964 ms: Scavenge 20.1 (23.2) -> 19.2 (23.7) MB, 2114.0 / 394.4 ms  allocation failure 
[2133:0x127c000]   576330 ms: Scavenge 20.1 (23.7) -> 19.2 (23.7) MB, 3364.2 / 31.0 ms  allocation failure 
[2133:0x127c000]   603664 ms: Scavenge 20.2 (23.7) -> 19.3 (23.7) MB, 3719.7 / 12.4 ms  allocation failure 

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x5e39330d <JSObject>
    3: normalizeStringPosix(aka normalizeStringPosix) [path.js:152] [bytecode=0x2112de11 offset=417](this=0x5e384125 <undefined>,path=0x39bffec9 <String[66]: /usr/lib/node_modules/.staging/es5-ext-aa91806b/array/to-array.js/>,allowAboveRoot=0x5e384189 <false>)
    4: resolve [path.js:1186] [bytecode=0x2112d9e1 offset=153](this=0x59ece925 <Object map = 0x2c0230b1>)
    5: arguments adaptor frame: 2->...

FATAL ERROR: Committing semi space failed. Allocation failed - process out of memory
Segmentation fault
``
I tried other `max_old_space_size` values as well.

**Comment by jsolderitsch** [comment]
I also tried to install using the palette manager and a similar failure was reported there.

**Comment by jsolderitsch** [comment]
I am running Omega2+ with the OS release: 0.3.2 b222 in case that matters.

**Comment by jsolderitsch** [comment]
I should note that I have not (yet) installed make and gcc for the Omega2 as discussed here:
http://docs.onion.io/omega2-docs/node-red-article.html

Do I need these parts installed for the Watson-iot nodes?

**Comment by jsolderitsch** [comment]
I followed the directions here:

https://github.com/pjobson/onion_omega2p_experiments/blob/master/docs/setting_up_sdcard_for_root_and_swap.md

to create an SD card for the omega2+ with both a Swap partition and a partition to extend the available file space.

Then the Watson-IoT nodes did install successfully.

So the issue can be closed I think IF the ReadME file is updated accordingly.

**Comment by johnwalicki** [comment]
I've updated the README - Closing issue.
